-- MISSING COLUMNS DETECTED. Run the following SQL:
ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_language TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_voice_gender TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_voice_rate FLOAT8;
ALTER TABLE users ADD COLUMN IF NOT EXISTS booking_language TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS booking_voice_gender TEXT;
